[FORMAT "WCOFF"]
[INSTRSET "i486p"]
[OPTIMIZE 1]
[OPTION 1]
[BITS 32]
	EXTERN	_init_gdtidt
	EXTERN	_init_pic
	EXTERN	_io_sti
	EXTERN	_fifo32_init
	EXTERN	_init_pit
	EXTERN	_init_keyboard
	EXTERN	_enable_mouse
	EXTERN	_io_out8
	EXTERN	_timer_alloc
	EXTERN	_timer_init
	EXTERN	_timer_settime
	EXTERN	_memtest
	EXTERN	_memman_init
	EXTERN	_memman_free
	EXTERN	_init_palette
	EXTERN	_shtctl_init
	EXTERN	_sheet_alloc
	EXTERN	_memman_alloc_4k
	EXTERN	_sheet_setbuf
	EXTERN	_init_screen8
	EXTERN	_init_mouse_cursor8
	EXTERN	_task_init
	EXTERN	_sprintf
	EXTERN	_task_alloc
	EXTERN	_task_b_main
	EXTERN	_task_run
	EXTERN	_sheet_slide
	EXTERN	_sheet_updown
	EXTERN	_memman_total
	EXTERN	_io_cli
	EXTERN	_fifo32_status
	EXTERN	_fifo32_get
	EXTERN	_boxfill8
	EXTERN	_sheet_refresh
	EXTERN	_mouse_decode
	EXTERN	_keytable.0
	EXTERN	_task_sleep
	EXTERN	_putfonts8_asc
[FILE "bootpack.c"]
[SECTION .data]
_keytable.0:
	DB	0
	DB	0
	DB	49
	DB	50
	DB	51
	DB	52
	DB	53
	DB	54
	DB	55
	DB	56
	DB	57
	DB	48
	DB	45
	DB	94
	DB	0
	DB	0
	DB	81
	DB	87
	DB	69
	DB	82
	DB	84
	DB	89
	DB	85
	DB	73
	DB	79
	DB	80
	DB	64
	DB	91
	DB	0
	DB	0
	DB	65
	DB	83
	DB	68
	DB	70
	DB	71
	DB	72
	DB	74
	DB	75
	DB	76
	DB	59
	DB	58
	DB	0
	DB	0
	DB	93
	DB	90
	DB	88
	DB	67
	DB	86
	DB	66
	DB	78
	DB	77
	DB	44
	DB	46
	DB	47
	DB	0
	DB	42
	DB	0
	DB	32
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	0
	DB	55
	DB	56
	DB	57
	DB	45
	DB	52
	DB	53
	DB	54
	DB	43
	DB	49
	DB	50
	DB	51
	DB	48
	DB	46
LC0:
	DB	"task_a",0x00
LC1:
	DB	"task_b%d",0x00
LC2:
	DB	"(%3d, %3d)",0x00
LC3:
	DB	"memory %dMB   free : %dKB",0x00
LC6:
	DB	"[lcr %4d %4d]",0x00
LC4:
	DB	"%02X",0x00
LC5:
	DB	" ",0x00
[SECTION .text]
	GLOBAL	_HariMain
_HariMain:
	PUSH	EBP
	MOV	EBP,ESP
	PUSH	EDI
	PUSH	ESI
	PUSH	EBX
	LEA	EBX,DWORD [-44+EBP]
	SUB	ESP,964
	CALL	_init_gdtidt
	CALL	_init_pic
	CALL	_io_sti
	LEA	EAX,DWORD [-604+EBP]
	PUSH	0
	PUSH	EAX
	PUSH	128
	PUSH	EBX
	CALL	_fifo32_init
	CALL	_init_pit
	PUSH	256
	PUSH	EBX
	CALL	_init_keyboard
	LEA	EAX,DWORD [-620+EBP]
	PUSH	EAX
	PUSH	512
	PUSH	EBX
	CALL	_enable_mouse
	ADD	ESP,36
	PUSH	248
	PUSH	33
	CALL	_io_out8
	PUSH	239
	PUSH	161
	CALL	_io_out8
	CALL	_timer_alloc
	PUSH	1
	PUSH	EBX
	LEA	EBX,DWORD [-892+EBP]
	PUSH	EAX
	MOV	DWORD [-912+EBP],EAX
	CALL	_timer_init
	PUSH	50
	PUSH	DWORD [-912+EBP]
	CALL	_timer_settime
	ADD	ESP,36
	PUSH	-1073741825
	PUSH	4194304
	CALL	_memtest
	PUSH	3932160
	MOV	DWORD [-924+EBP],EAX
	CALL	_memman_init
	PUSH	647168
	PUSH	4096
	PUSH	3932160
	CALL	_memman_free
	MOV	EAX,DWORD [-924+EBP]
	SUB	EAX,4194304
	PUSH	EAX
	PUSH	4194304
	PUSH	3932160
	CALL	_memman_free
	ADD	ESP,36
	CALL	_init_palette
	MOVSX	EAX,WORD [4086]
	PUSH	EAX
	MOVSX	EAX,WORD [4084]
	PUSH	EAX
	PUSH	DWORD [4088]
	PUSH	3932160
	CALL	_shtctl_init
	PUSH	EAX
	MOV	DWORD [-928+EBP],EAX
	CALL	_sheet_alloc
	PUSH	DWORD [-928+EBP]
	MOV	DWORD [-932+EBP],EAX
	CALL	_sheet_alloc
	PUSH	DWORD [-928+EBP]
	MOV	DWORD [-936+EBP],EAX
	CALL	_sheet_alloc
	MOVSX	EDX,WORD [4086]
	MOV	DWORD [-940+EBP],EAX
	MOVSX	EAX,WORD [4084]
	IMUL	EAX,EDX
	PUSH	EAX
	PUSH	3932160
	CALL	_memman_alloc_4k
	ADD	ESP,36
	MOV	ESI,EAX
	PUSH	8320
	PUSH	3932160
	CALL	_memman_alloc_4k
	PUSH	-1
	MOV	EDI,EAX
	MOVSX	EAX,WORD [4086]
	PUSH	EAX
	MOVSX	EAX,WORD [4084]
	PUSH	EAX
	PUSH	ESI
	PUSH	DWORD [-932+EBP]
	CALL	_sheet_setbuf
	PUSH	99
	PUSH	16
	PUSH	16
	PUSH	EBX
	PUSH	DWORD [-936+EBP]
	CALL	_sheet_setbuf
	ADD	ESP,48
	PUSH	-1
	PUSH	52
	PUSH	160
	PUSH	EDI
	PUSH	DWORD [-940+EBP]
	CALL	_sheet_setbuf
	MOVSX	EAX,WORD [4086]
	PUSH	EAX
	MOVSX	EAX,WORD [4084]
	PUSH	EAX
	PUSH	ESI
	XOR	ESI,ESI
	CALL	_init_screen8
	ADD	ESP,32
	PUSH	99
	PUSH	EBX
	MOV	EBX,2
	CALL	_init_mouse_cursor8
	PUSH	1
	PUSH	LC0
	PUSH	52
	PUSH	160
	PUSH	EDI
	CALL	_make_window8
	PUSH	7
	PUSH	16
	PUSH	128
	PUSH	28
	PUSH	8
	PUSH	DWORD [-940+EBP]
	CALL	_make_textbox8
	ADD	ESP,52
	MOVSX	EAX,WORD [4084]
	MOV	DWORD [-920+EBP],8
	LEA	ECX,DWORD [-16+EAX]
	MOV	EAX,ECX
	CDQ
	IDIV	EBX
	MOV	DWORD [-952+EBP],EAX
	MOV	DWORD [-916+EBP],EAX
	MOVSX	EAX,WORD [4086]
	PUSH	3932160
	LEA	ECX,DWORD [-44+EAX]
	MOV	EAX,ECX
	CDQ
	IDIV	EBX
	MOV	DWORD [-956+EBP],EAX
	MOV	EDI,EAX
	CALL	_task_init
	MOV	DWORD [-944+EBP],EAX
	MOV	DWORD [-20+EBP],EAX
	POP	EAX
L6:
	PUSH	DWORD [-928+EBP]
	CALL	_sheet_alloc
	PUSH	7488
	PUSH	3932160
	MOV	DWORD [-636+EBP+ESI*4],EAX
	CALL	_memman_alloc_4k
	PUSH	-1
	MOV	EBX,EAX
	PUSH	52
	PUSH	144
	PUSH	EAX
	PUSH	DWORD [-636+EBP+ESI*4]
	CALL	_sheet_setbuf
	LEA	EAX,DWORD [-92+EBP]
	ADD	ESP,32
	PUSH	ESI
	PUSH	LC1
	PUSH	EAX
	CALL	_sprintf
	LEA	EDX,DWORD [-92+EBP]
	PUSH	0
	PUSH	EDX
	PUSH	52
	PUSH	144
	PUSH	EBX
	CALL	_make_window8
	ADD	ESP,32
	CALL	_task_alloc
	PUSH	65536
	MOV	EBX,EAX
	PUSH	3932160
	MOV	DWORD [-908+EBP+ESI*4],EAX
	CALL	_memman_alloc_4k
	ADD	EAX,65528
	MOV	DWORD [64+EBX],EAX
	MOV	EBX,DWORD [-636+EBP+ESI*4]
	MOV	EAX,DWORD [-908+EBP+ESI*4]
	INC	ESI
	MOV	ECX,DWORD [64+EAX]
	MOV	DWORD [40+EAX],_task_b_main
	MOV	DWORD [80+EAX],8
	MOV	DWORD [84+EAX],16
	MOV	DWORD [88+EAX],8
	MOV	DWORD [92+EAX],8
	MOV	DWORD [96+EAX],8
	MOV	DWORD [100+EAX],8
	MOV	DWORD [4+ECX],EBX
	PUSH	EAX
	CALL	_task_run
	ADD	ESP,12
	CMP	ESI,2
	JLE	L6
	PUSH	0
	LEA	EBX,DWORD [-92+EBP]
	PUSH	0
	PUSH	DWORD [-932+EBP]
	CALL	_sheet_slide
	PUSH	56
	PUSH	168
	PUSH	DWORD [-636+EBP]
	CALL	_sheet_slide
	PUSH	116
	PUSH	8
	PUSH	DWORD [-632+EBP]
	CALL	_sheet_slide
	ADD	ESP,36
	PUSH	116
	PUSH	168
	PUSH	DWORD [-628+EBP]
	CALL	_sheet_slide
	PUSH	DWORD [-956+EBP]
	PUSH	DWORD [-952+EBP]
	PUSH	DWORD [-936+EBP]
	CALL	_sheet_slide
	PUSH	56
	PUSH	8
	PUSH	DWORD [-940+EBP]
	CALL	_sheet_slide
	ADD	ESP,36
	PUSH	0
	PUSH	DWORD [-932+EBP]
	CALL	_sheet_updown
	PUSH	1
	PUSH	DWORD [-636+EBP]
	CALL	_sheet_updown
	PUSH	2
	PUSH	DWORD [-632+EBP]
	CALL	_sheet_updown
	PUSH	3
	PUSH	DWORD [-628+EBP]
	CALL	_sheet_updown
	ADD	ESP,32
	PUSH	4
	PUSH	DWORD [-940+EBP]
	CALL	_sheet_updown
	PUSH	5
	PUSH	DWORD [-936+EBP]
	CALL	_sheet_updown
	LEA	EAX,DWORD [-92+EBP]
	PUSH	DWORD [-956+EBP]
	PUSH	DWORD [-952+EBP]
	PUSH	LC2
	PUSH	EAX
	CALL	_sprintf
	LEA	EDX,DWORD [-92+EBP]
	ADD	ESP,32
	PUSH	10
	PUSH	EDX
	PUSH	14
	PUSH	7
	PUSH	0
	PUSH	0
	PUSH	DWORD [-932+EBP]
	CALL	_putfonts8_asc_sht
	PUSH	3932160
	CALL	_memman_total
	SHR	DWORD [-924+EBP],20
	SHR	EAX,10
	MOV	DWORD [ESP],EAX
	PUSH	DWORD [-924+EBP]
	PUSH	LC3
	PUSH	EBX
	CALL	_sprintf
	ADD	ESP,44
	PUSH	40
	PUSH	EBX
	PUSH	14
	PUSH	7
	PUSH	32
	PUSH	0
	PUSH	DWORD [-932+EBP]
	CALL	_putfonts8_asc_sht
	ADD	ESP,28
L7:
	LEA	EBX,DWORD [-44+EBP]
	CALL	_io_cli
	PUSH	EBX
	CALL	_fifo32_status
	POP	ESI
	TEST	EAX,EAX
	JE	L33
	PUSH	EBX
	CALL	_fifo32_get
	MOV	ESI,EAX
	CALL	_io_sti
	POP	EDX
	LEA	EAX,DWORD [-256+ESI]
	CMP	EAX,255
	JBE	L34
	LEA	EAX,DWORD [-512+ESI]
	CMP	EAX,255
	JBE	L35
	CMP	ESI,1
	JG	L7
	TEST	ESI,ESI
	JE	L28
	PUSH	0
	PUSH	EBX
	XOR	EBX,EBX
	PUSH	DWORD [-912+EBP]
	CALL	_timer_init
L32:
	ADD	ESP,12
	PUSH	50
	PUSH	DWORD [-912+EBP]
	CALL	_timer_settime
	MOV	EDX,DWORD [-940+EBP]
	MOV	EAX,DWORD [-920+EBP]
	PUSH	43
	ADD	EAX,7
	PUSH	EAX
	PUSH	28
	PUSH	DWORD [-920+EBP]
	PUSH	EBX
	PUSH	DWORD [4+EDX]
	PUSH	DWORD [EDX]
	CALL	_boxfill8
	MOV	EAX,DWORD [-920+EBP]
	ADD	ESP,36
	ADD	EAX,8
	PUSH	44
	PUSH	EAX
	PUSH	28
	PUSH	DWORD [-920+EBP]
	PUSH	DWORD [-940+EBP]
	CALL	_sheet_refresh
	ADD	ESP,20
	LEA	ESP,DWORD [-12+EBP]
	POP	EBX
	POP	ESI
	POP	EDI
	POP	EBP
	RET
L28:
	PUSH	1
	PUSH	EBX
	MOV	EBX,7
	PUSH	DWORD [-912+EBP]
	CALL	_timer_init
	JMP	L32
L35:
	PUSH	EAX
	LEA	EAX,DWORD [-620+EBP]
	PUSH	EAX
	CALL	_mouse_decode
	POP	EDX
	POP	ECX
	TEST	EAX,EAX
	JE	L7
	PUSH	DWORD [-612+EBP]
	PUSH	DWORD [-616+EBP]
	PUSH	LC6
	LEA	EBX,DWORD [-92+EBP]
	PUSH	EBX
	CALL	_sprintf
	ADD	ESP,16
	MOV	EAX,DWORD [-608+EBP]
	TEST	EAX,1
	JE	L18
	MOV	BYTE [-91+EBP],76
L18:
	TEST	EAX,2
	JE	L19
	MOV	BYTE [-89+EBP],82
L19:
	AND	EAX,4
	JE	L20
	MOV	BYTE [-90+EBP],67
L20:
	PUSH	15
	PUSH	EBX
	PUSH	14
	PUSH	7
	PUSH	16
	PUSH	32
	PUSH	DWORD [-932+EBP]
	CALL	_putfonts8_asc_sht
	MOV	EAX,DWORD [-616+EBP]
	ADD	EDI,DWORD [-612+EBP]
	ADD	ESP,28
	ADD	DWORD [-916+EBP],EAX
	JS	L36
L21:
	TEST	EDI,EDI
	JS	L37
L22:
	MOVSX	EAX,WORD [4084]
	DEC	EAX
	CMP	DWORD [-916+EBP],EAX
	JLE	L23
	MOV	DWORD [-916+EBP],EAX
L23:
	MOVSX	EAX,WORD [4086]
	DEC	EAX
	CMP	EDI,EAX
	JLE	L24
	MOV	EDI,EAX
L24:
	PUSH	EDI
	PUSH	DWORD [-916+EBP]
	PUSH	LC2
	PUSH	EBX
	CALL	_sprintf
	PUSH	10
	PUSH	EBX
	PUSH	14
	PUSH	7
	PUSH	0
	PUSH	0
	PUSH	DWORD [-932+EBP]
	CALL	_putfonts8_asc_sht
	ADD	ESP,44
	PUSH	EDI
	PUSH	DWORD [-916+EBP]
	PUSH	DWORD [-936+EBP]
	CALL	_sheet_slide
	ADD	ESP,12
	TEST	DWORD [-608+EBP],1
	JE	L7
	LEA	EAX,DWORD [-8+EDI]
	PUSH	EAX
	MOV	EAX,DWORD [-916+EBP]
	SUB	EAX,80
	PUSH	EAX
	PUSH	DWORD [-940+EBP]
	CALL	_sheet_slide
	ADD	ESP,12
	JMP	L7
L37:
	XOR	EDI,EDI
	JMP	L22
L36:
	MOV	DWORD [-916+EBP],0
	JMP	L21
L34:
	PUSH	EAX
	LEA	EBX,DWORD [-92+EBP]
	PUSH	LC4
	PUSH	EBX
	CALL	_sprintf
	PUSH	2
	PUSH	EBX
	PUSH	14
	PUSH	7
	PUSH	16
	PUSH	0
	PUSH	DWORD [-932+EBP]
	CALL	_putfonts8_asc_sht
	MOV	CL,BYTE [_keytable.0-256+ESI]
	ADD	ESP,40
	CMP	ESI,339
	SETLE	BYTE [-976+EBP]
	MOV	DL,BYTE [-976+EBP]
	TEST	CL,CL
	SETNE	AL
	AND	EAX,EDX
	AND	EAX,1
	JE	L13
	CMP	DWORD [-920+EBP],143
	JLE	L38
L13:
	CMP	ESI,270
	JE	L39
L14:
	MOV	EAX,DWORD [-920+EBP]
	PUSH	43
	ADD	EAX,7
	MOV	EBX,DWORD [-940+EBP]
	PUSH	EAX
	PUSH	28
	PUSH	DWORD [-920+EBP]
	PUSH	7
	PUSH	DWORD [4+EBX]
	PUSH	DWORD [EBX]
	CALL	_boxfill8
	MOV	EAX,DWORD [-920+EBP]
	PUSH	44
	ADD	EAX,8
	PUSH	EAX
	PUSH	28
	PUSH	DWORD [-920+EBP]
	PUSH	EBX
	CALL	_sheet_refresh
	ADD	ESP,48
	JMP	L7
L39:
	CMP	DWORD [-920+EBP],8
	JLE	L14
	PUSH	1
	PUSH	LC5
	PUSH	7
	PUSH	0
	PUSH	28
	PUSH	DWORD [-920+EBP]
	PUSH	DWORD [-940+EBP]
	CALL	_putfonts8_asc_sht
	ADD	ESP,28
	SUB	DWORD [-920+EBP],8
	JMP	L14
L38:
	PUSH	1
	MOV	BYTE [-92+EBP],CL
	PUSH	EBX
	PUSH	7
	PUSH	0
	PUSH	28
	PUSH	DWORD [-920+EBP]
	PUSH	DWORD [-940+EBP]
	MOV	BYTE [-91+EBP],0
	CALL	_putfonts8_asc_sht
	ADD	ESP,28
	ADD	DWORD [-920+EBP],8
	JMP	L13
L33:
	PUSH	DWORD [-944+EBP]
	CALL	_task_sleep
	CALL	_io_sti
	POP	ECX
	JMP	L7
[SECTION .data]
_closebtn.1:
	DB	"OOOOOOOOOOOOOOO@"
	DB	"OQQQQQQQQQQQQQ$@"
	DB	"OQQQQQQQQQQQQQ$@"
	DB	"OQQQ@@QQQQ@@QQ$@"
	DB	"OQQQQ@@QQ@@QQQ$@"
	DB	"OQQQQQ@@@@QQQQ$@"
	DB	"OQQQQQQ@@QQQQQ$@"
	DB	"OQQQQQ@@@@QQQQ$@"
	DB	"OQQQQ@@QQ@@QQQ$@"
	DB	"OQQQ@@QQQQ@@QQ$@"
	DB	"OQQQQQQQQQQQQQ$@"
	DB	"OQQQQQQQQQQQQQ$@"
	DB	"O$$$$$$$$$$$$$$@"
	DB	"@@@@@@@@@@@@@@@@"
[SECTION .text]
	GLOBAL	_make_window8
_make_window8:
	PUSH	EBP
	MOV	EBP,ESP
	PUSH	EDI
	PUSH	ESI
	PUSH	EBX
	SUB	ESP,12
	CMP	BYTE [24+EBP],0
	JE	L41
	MOV	BYTE [-17+EBP],12
L42:
	MOV	EAX,DWORD [12+EBP]
	PUSH	0
	DEC	EAX
	PUSH	EAX
	MOV	DWORD [-24+EBP],EAX
	PUSH	0
	PUSH	0
	PUSH	8
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	MOV	ESI,DWORD [12+EBP]
	PUSH	1
	SUB	ESI,2
	PUSH	ESI
	PUSH	1
	PUSH	1
	PUSH	7
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	MOV	EDI,DWORD [16+EBP]
	ADD	ESP,56
	DEC	EDI
	PUSH	EDI
	PUSH	0
	PUSH	0
	PUSH	0
	PUSH	8
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	MOV	EBX,DWORD [16+EBP]
	SUB	EBX,2
	PUSH	EBX
	PUSH	1
	PUSH	1
	PUSH	1
	PUSH	7
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	ADD	ESP,56
	PUSH	EBX
	PUSH	ESI
	PUSH	1
	PUSH	ESI
	PUSH	15
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	PUSH	EDI
	PUSH	DWORD [-24+EBP]
	PUSH	0
	PUSH	DWORD [-24+EBP]
	PUSH	0
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	MOV	EAX,DWORD [16+EBP]
	ADD	ESP,56
	SUB	EAX,3
	PUSH	EAX
	MOV	EAX,DWORD [12+EBP]
	SUB	EAX,3
	PUSH	EAX
	PUSH	2
	PUSH	2
	PUSH	8
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	MOV	EAX,DWORD [12+EBP]
	PUSH	20
	SUB	EAX,4
	PUSH	EAX
	PUSH	3
	PUSH	3
	MOVZX	EAX,BYTE [-17+EBP]
	PUSH	EAX
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	ADD	ESP,56
	PUSH	EBX
	PUSH	ESI
	PUSH	EBX
	PUSH	1
	PUSH	15
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	PUSH	EDI
	PUSH	DWORD [-24+EBP]
	PUSH	EDI
	XOR	EDI,EDI
	PUSH	0
	PUSH	0
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_boxfill8
	ADD	ESP,56
	PUSH	DWORD [20+EBP]
	MOVSX	EAX,BYTE [-17+EBP]
	PUSH	EAX
	PUSH	4
	PUSH	24
	PUSH	DWORD [12+EBP]
	PUSH	DWORD [8+EBP]
	CALL	_putfonts8_asc
	ADD	ESP,24
	IMUL	EBX,DWORD [12+EBP],5
	MOV	DWORD [-16+EBP],0
L58:
	MOV	EAX,DWORD [12+EBP]
	MOV	EDX,DWORD [8+EBP]
	ADD	EAX,EBX
	XOR	ESI,ESI
	LEA	ECX,DWORD [-21+EDX+EAX*1]
L57:
	MOV	DL,BYTE [_closebtn.1+ESI+EDI*1]
	CMP	DL,64
	JE	L63
	CMP	DL,36
	JE	L64
	CMP	DL,81
	MOV	DL,8
	SETNE	AL
	SUB	DL,AL
L52:
	INC	ESI
	MOV	BYTE [ECX],DL
	INC	ECX
	CMP	ESI,15
	JLE	L57
	INC	DWORD [-16+EBP]
	ADD	EDI,16
	ADD	EBX,DWORD [12+EBP]
	CMP	DWORD [-16+EBP],13
	JLE	L58
	LEA	ESP,DWORD [-12+EBP]
	POP	EBX
	POP	ESI
	POP	EDI
	POP	EBP
	RET
L64:
	MOV	DL,15
	JMP	L52
L63:
	XOR	EDX,EDX
	JMP	L52
L41:
	MOV	BYTE [-17+EBP],15
	JMP	L42
	GLOBAL	_putfonts8_asc_sht
_putfonts8_asc_sht:
	PUSH	EBP
	MOV	EBP,ESP
	PUSH	EDI
	PUSH	ESI
	PUSH	EBX
	SUB	ESP,12
	MOV	EAX,DWORD [20+EBP]
	MOV	ESI,DWORD [8+EBP]
	MOV	DWORD [-16+EBP],EAX
	MOV	EBX,DWORD [12+EBP]
	MOV	EAX,DWORD [28+EBP]
	MOV	EDI,DWORD [16+EBP]
	MOV	ECX,DWORD [24+EBP]
	MOV	DWORD [-20+EBP],EAX
	MOV	EDX,DWORD [32+EBP]
	TEST	ESI,ESI
	JE	L65
	LEA	EDX,DWORD [EBX+EDX*8]
	LEA	EAX,DWORD [15+EDI]
	PUSH	EAX
	MOV	EAX,EDX
	DEC	EAX
	MOV	DWORD [-24+EBP],EDX
	PUSH	EAX
	PUSH	EDI
	PUSH	EBX
	MOVZX	EAX,CL
	PUSH	EAX
	PUSH	DWORD [4+ESI]
	PUSH	DWORD [ESI]
	CALL	_boxfill8
	PUSH	DWORD [-20+EBP]
	MOVSX	EAX,BYTE [-16+EBP]
	PUSH	EAX
	PUSH	EDI
	PUSH	EBX
	PUSH	DWORD [4+ESI]
	PUSH	DWORD [ESI]
	CALL	_putfonts8_asc
	MOV	DWORD [8+EBP],ESI
	LEA	EAX,DWORD [16+EDI]
	MOV	DWORD [16+EBP],EDI
	MOV	DWORD [24+EBP],EAX
	MOV	DWORD [12+EBP],EBX
	MOV	EAX,DWORD [-24+EBP]
	ADD	ESP,52
	MOV	DWORD [20+EBP],EAX
	LEA	ESP,DWORD [-12+EBP]
	POP	EBX
	POP	ESI
	POP	EDI
	POP	EBP
	JMP	_sheet_refresh
L65:
	LEA	ESP,DWORD [-12+EBP]
	POP	EBX
	POP	ESI
	POP	EDI
	POP	EBP
	RET
	GLOBAL	_make_textbox8
_make_textbox8:
	PUSH	EBP
	MOV	EBP,ESP
	PUSH	EDI
	PUSH	ESI
	PUSH	EBX
	SUB	ESP,20
	MOV	EAX,DWORD [12+EBP]
	MOV	ESI,DWORD [16+EBP]
	ADD	EAX,DWORD [20+EBP]
	SUB	ESI,3
	PUSH	ESI
	MOV	DWORD [-16+EBP],EAX
	MOV	EAX,DWORD [16+EBP]
	ADD	EAX,DWORD [24+EBP]
	MOV	DWORD [-20+EBP],EAX
	MOV	EAX,DWORD [-16+EBP]
	INC	EAX
	PUSH	EAX
	MOV	DWORD [-24+EBP],EAX
	MOV	EAX,DWORD [12+EBP]
	PUSH	ESI
	SUB	EAX,2
	PUSH	EAX
	MOV	DWORD [-28+EBP],EAX
	MOV	EAX,DWORD [8+EBP]
	PUSH	15
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EDI,DWORD [12+EBP]
	MOV	EAX,DWORD [-20+EBP]
	SUB	EDI,3
	INC	EAX
	PUSH	EAX
	MOV	DWORD [-32+EBP],EAX
	PUSH	EDI
	MOV	EAX,DWORD [8+EBP]
	PUSH	ESI
	PUSH	EDI
	PUSH	15
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EAX,DWORD [8+EBP]
	ADD	ESP,56
	MOV	EBX,DWORD [-20+EBP]
	ADD	EBX,2
	PUSH	EBX
	PUSH	DWORD [-24+EBP]
	PUSH	EBX
	PUSH	EDI
	PUSH	7
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EAX,DWORD [-16+EBP]
	PUSH	EBX
	ADD	EAX,2
	PUSH	EAX
	PUSH	ESI
	PUSH	EAX
	MOV	EAX,DWORD [8+EBP]
	PUSH	7
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EAX,DWORD [8+EBP]
	ADD	ESP,56
	MOV	EBX,DWORD [16+EBP]
	SUB	EBX,2
	MOV	EDI,DWORD [12+EBP]
	PUSH	EBX
	DEC	EDI
	PUSH	DWORD [-16+EBP]
	PUSH	EBX
	PUSH	EDI
	PUSH	0
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EAX,DWORD [8+EBP]
	PUSH	DWORD [-20+EBP]
	PUSH	DWORD [-28+EBP]
	PUSH	EBX
	PUSH	DWORD [-28+EBP]
	PUSH	0
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EAX,DWORD [8+EBP]
	ADD	ESP,56
	PUSH	DWORD [-32+EBP]
	PUSH	DWORD [-16+EBP]
	PUSH	DWORD [-32+EBP]
	PUSH	DWORD [-28+EBP]
	PUSH	8
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EAX,DWORD [8+EBP]
	PUSH	DWORD [-32+EBP]
	PUSH	DWORD [-24+EBP]
	PUSH	EBX
	PUSH	DWORD [-24+EBP]
	PUSH	8
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	MOV	EAX,DWORD [16+EBP]
	ADD	ESP,56
	DEC	EAX
	PUSH	DWORD [-20+EBP]
	PUSH	DWORD [-16+EBP]
	PUSH	EAX
	PUSH	EDI
	MOVZX	EAX,BYTE [28+EBP]
	PUSH	EAX
	MOV	EAX,DWORD [8+EBP]
	PUSH	DWORD [4+EAX]
	PUSH	DWORD [EAX]
	CALL	_boxfill8
	LEA	ESP,DWORD [-12+EBP]
	POP	EBX
	POP	ESI
	POP	EDI
	POP	EBP
	RET
